import React from "react";
import { BarChart3, Trophy } from "lucide-react";
import "../styles/placeholder.css";

export const Challenges: React.FC = () => (
  <div
    className="
      placeholder-container
    "
  >
    <div
      className="
        placeholder-content
      "
    >
      <Trophy
        size={60}
        className="
          placeholder-icon
        "
      />
      <h1
        className="
          page-title
        "
      >
        Desafios CTF
      </h1>
      <p
        className="
          placeholder-subtitle
        "
      >
        Desafios Capture The Flag em desenvolvimento
      </p>
      <div
        className="
          placeholder-features
        "
      >
        <div
          className="
            feature
          "
        >
          <span
            className="
              feature-icon
            "
          >
            🔐
          </span>
          <span>Criptografia</span>
        </div>
        <div
          className="
            feature
          "
        >
          <span
            className="
              feature-icon
            "
          >
            🔍
          </span>
          <span>Engenharia Reversa</span>
        </div>
        <div
          className="
            feature
          "
        >
          <span
            className="
              feature-icon
            "
          >
            🕸️
          </span>
          <span>Web Exploitation</span>
        </div>
        <div
          className="
            feature
          "
        >
          <span
            className="
              feature-icon
            "
          >
            🔬
          </span>
          <span>Forense</span>
        </div>
        <div
          className="
            feature
          "
        >
          <span
            className="
              feature-icon
            "
          >
            🎯
          </span>
          <span>Pwning</span>
        </div>
      </div>
    </div>
  </div>
);

export const Ranking: React.FC = () => (
  <div
    className="
      placeholder-container
    "
  >
    <div
      className="
        placeholder-content
      "
    >
      <BarChart3
        size={60}
        className="
          placeholder-icon
        "
      />
      <h1
        className="
          page-title
        "
      >
        Ranking Global
      </h1>
      <p
        className="
          placeholder-subtitle
        "
      >
        Leaderboard de hackers em desenvolvimento
      </p>
      <div
        className="
          placeholder-stats
        "
      >
        <div
          className="
            stat
          "
        >
          <span
            className="
              stat-number
            "
          >
            1,234
          </span>
          <span
            className="
              stat-label
            "
          >
            Hackers Ativos
          </span>
        </div>
        <div
          className="
            stat
          "
        >
          <span
            className="
              stat-number
            "
          >
            5,678
          </span>
          <span
            className="
              stat-label
            "
          >
            Missões Completas
          </span>
        </div>
        <div
          className="
            stat
          "
        >
          <span
            className="
              stat-number
            "
          >
            #42
          </span>
          <span
            className="
              stat-label
            "
          >
            Sua Posição
          </span>
        </div>
      </div>
    </div>
  </div>
);

export const Learning: React.FC = () => (
  <div
    className="
      placeholder-container
    "
  >
    <div
      className="
        placeholder-content
      "
    >
      <Trophy
        size={60}
        className="
          placeholder-icon
        "
      />
      <h1
        className="
          page-title
        "
      >
        Centro de Aprendizado
      </h1>
      <p
        className="
          placeholder-subtitle
        "
      >
        Cursos e tutoriais em desenvolvimento
      </p>
      <div
        className="
          placeholder-features
        "
      >
        <div
          className="
            feature
          "
        >
          <span
            className="
              feature-icon
            "
          >
            📹
          </span>
          <span>Videoaulas</span>
        </div>
        <div
          className="
            feature
          "
        >
          <span
            className="
              feature-icon
            "
          >
            📚
          </span>
          <span>Guias Completos</span>
        </div>
        <div
          className="
            feature
          "
        >
          <span
            className="
              feature-icon
            "
          >
            🗂️
          </span>
          <span>Glossário</span>
        </div>
        <div
          className="
            feature
          "
        >
          <span
            className="
              feature-icon
            "
          >
            🛣️
          </span>
          <span>Roadmaps</span>
        </div>
      </div>
    </div>
  </div>
);

export const BugBounty: React.FC = () => (
  <div
    className="
      placeholder-container
    "
  >
    <div
      className="
        placeholder-content
      "
    >
      <Trophy
        size={60}
        className="
          placeholder-icon
        "
      />
      <h1
        className="
          page-title
        "
      >
        Bug Bounty
      </h1>
      <p
        className="
          placeholder-subtitle
        "
      >
        Programas de recompensa em desenvolvimento
      </p>
      <div
        className="
          placeholder-features
        "
      >
        <div
          className="
            feature
          "
        >
          <span
            className="
              feature-icon
            "
          >
            🎯
          </span>
          <span>Programas Verificados</span>
        </div>
        <div
          className="
            feature
          "
        >
          <span
            className="
              feature-icon
            "
          >
            💰
          </span>
          <span>Recompensas</span>
        </div>
        <div
          className="
            feature
          "
        >
          <span
            className="
              feature-icon
            "
          >
            📋
          </span>
          <span>Escopo e Regras</span>
        </div>
        <div
          className="
            feature
          "
        >
          <span
            className="
              feature-icon
            "
          >
            📊
          </span>
          <span>Estatísticas</span>
        </div>
      </div>
    </div>
  </div>
);

export const Admin: React.FC = () => (
  <div
    className="
      placeholder-container
    "
  >
    <div
      className="
        placeholder-content
      "
    >
      <Trophy
        size={60}
        className="
          placeholder-icon
        "
      />
      <h1
        className="
          page-title
        "
      >
        Painel Administrativo
      </h1>
      <p
        className="
          placeholder-subtitle
        "
      >
        Gerenciamento de plataforma em desenvolvimento
      </p>
      <div
        className="
          placeholder-features
        "
      >
        <div
          className="
            feature
          "
        >
          <span
            className="
              feature-icon
            "
          >
            👥
          </span>
          <span>Gerenciar Usuários</span>
        </div>
        <div
          className="
            feature
          "
        >
          <span
            className="
              feature-icon
            "
          >
            🧪
          </span>
          <span>Controlar Labs</span>
        </div>
        <div
          className="
            feature
          "
        >
          <span
            className="
              feature-icon
            "
          >
            📝
          </span>
          <span>Criar Desafios</span>
        </div>
        <div
          className="
            feature
          "
        >
          <span
            className="
              feature-icon
            "
          >
            📊
          </span>
          <span>Visualizar Logs</span>
        </div>
      </div>
    </div>
  </div>
);
